################################################################################
#
# MUPEN64PLUS-NEXT-RAW
#
################################################################################
# Version: Commits on Oct 18, 2019
LIBRETRO_MUPEN64PLUS_NEXT_RAW_VERSION = 2027bcc994246d23d70c5a12c79c22899a889552
LIBRETRO_MUPEN64PLUS_NEXT_RAW_SITE = $(call github,CEnnis91,mupen64plus-libretro-nx,$(LIBRETRO_MUPEN64PLUS_NEXT_RAW_VERSION))
LIBRETRO_MUPEN64PLUS_NEXT_RAW_LICENSE = GPLv2
LIBRETRO_MUPEN64PLUS_NEXT_RAW_DEPENDENCIES = host-nasm

ifeq ($(BR2_PACKAGE_RPI_USERLAND),y)
	LIBRETRO_MUPEN64PLUS_DEPENDENCIES += rpi-userland
endif

LIBRETRO_MUPEN64PLUS_NEXT_RAW_SUPP_OPT=

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RPI3),y)
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM=rpi3

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RPI2),y)
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM=rpi2

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_XU4)$(BR2_PACKAGE_BATOCERA_TARGET_LEGACYXU4),y)
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM=odroid-ODROID-XU

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_C2),y)
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM=odroid-ODROIDC

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_S905),y)
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM=unix
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_SUPP_OPT=ARCH=aarch64

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_S912),y)
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM=unix
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_SUPP_OPT=ARCH=aarch64

else ifeq ($(BR2_x86_i586),y)
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM=unix
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_SUPP_OPT=ARCH=i686

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_ROCKPRO64),y)
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM=RK3399

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_ODROIDN2),y)
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM=odroidn2

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_TINKERBOARD),y)
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM=RK3288

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_MIQI),y)
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM=RK3288

else
	LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM=$(LIBRETRO_PLATFORM)
endif

define LIBRETRO_MUPEN64PLUS_NEXT_RAW_BUILD_CMDS
	PATH=$(BR_PATH) CFLAGS="$(TARGET_CFLAGS)" CXXFLAGS="$(TARGET_CXXFLAGS)" CPPFLAGS="$(TARGET_CPPFLAGS)" \
		$(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" LD="$(TARGET_LD)" \
		RANLIB="$(TARGET_RANLIB)" AR="$(TARGET_AR)" -C $(@D)/ \
		-f Makefile platform="$(LIBRETRO_MUPEN64PLUS_NEXT_RAW_PLATFORM)" \
		$(LIBRETRO_MUPEN64PLUS_NEXT_RAW_SUPP_OPT)
endef

define LIBRETRO_MUPEN64PLUS_NEXT_RAW_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/mupen64plus_next_raw_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/mupen64plus-next-raw_libretro.so
endef

$(eval $(generic-package))
